cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('add/<slug:slug>/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<slug:slug>/',views.item_clear , name='item_clear'),
    path('item_increment/<slug:slug>/',views.item_increment , name='item_increment'),
    path('item_decrement/<slug:slug>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views



app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<slug:slug>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from products.models import Product
from django.contrib.auth.decorators import login_required
from django.contrib import messages,auth
from django.views.decorators.http import require_POST
from .cart import Cart
from orders.models import Order

@login_required(login_url="/users/login")
def cart_add(request, slug):
	cart = Cart(request)
	product = Product.objects.get(slug=slug)
	cart.add(product=product)
	return redirect('/')

@login_required(login_url="/users/login")
def cart_detail(request):
	sub = []
	qty = []
	total = 0
	for key,value in request.session['cart'].items():
		sub.append(float(value['price']) * float(value['quantity']))
		qty.append(int(value['quantity']))
	for s in sub:
		total = total + s
	context = {
    	'title' : 'My Cart',
    	'sub' : sub,
    	'total' : total
    }
	return render(request,'cart/cart_detail.html',context)

@login_required(login_url="/users/login")
def item_clear(request,slug):
	cart = Cart(request)
	product = Product.objects.get(slug=slug)
	cart.remove(product)
	return redirect('cart:cart_detail')

@login_required(login_url="/users/login")
def item_increment(request,slug):
	cart = Cart(request)
	product = Product.objects.get(slug=slug)
	cart.add(product=product)
	return redirect('cart:cart_detail')

@login_required(login_url="/users/login")
def item_decrement(request,slug):
	cart = Cart(request)
	product = Product.objects.get(slug=slug)
	cart.decrement(product=product)
	return redirect('cart:cart_detail')

@login_required(login_url="/users/login")
def cart_clear(request):
	cart = Cart(request)
	cart.clear()
	return redirect('cart:cart_detail')

@login_required(login_url="/users/login")
def checkout(request):
	sub = []
	qty = []
	total = 0
	if len(request.session['cart']) != 0:
		for key,value in request.session['cart'].items():
			sub.append(float(value['price']) * float(value['quantity']))
			qty.append(int(value['quantity']))
		for s in sub:
			total = total + s
		context = {
	    	'title' : 'CheckOut',
	    	'sub' : sub,
	    	'total' : total
	    }
		return render(request,'cart/checkout.html',context)
	else:
		messages.info(request,"Your cart Is Empty")
		return redirect('/')

@login_required(login_url="/users/login")
def confrm_checkout(request):
	if len(request.session['cart']) != 0:
		if request.method == 'POST':
			name = request.POST['name']
			phone = request.POST['phonenumber']
			email = request.POST['email']
			address = request.POST['address']
			user_id = request.user.id
			if name and phone and email and address:
				for key,value in request.session['cart'].items():
					item = value['title']
					quantity = value['quantity']
					price = value['price']
					total = (float(quantity) * float(price))
					order = Order(item=item,quantity=quantity,price=price,total=total,name=name,phone=phone,email=email,address=address,user_id=user_id)
					order.save()
				cart_clear(request)
				messages.success(request,'Order Created SuccessFully')
				return redirect('users:dashboard')
			else:
				messages.info(request,'Filled All The Field')
				return redirect('cart:checkout')
		else:
			messages.warning(request,'SomeThing Went Wrong')
			return redirect('cart:checkout')
	else:
		messages.info(request,"Your cart Is Empty")
		return redirect('/')

templates/cart/cart_detail.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}


  <div class="col-md-12">

	<table class="table table-inverse mt-3">
		<thead>
			<tr>
				<th>Image</th>
				<th>Title</th>
				<th>Price</th>
				<th>Quantity</th>
				<th></th>
				<th>SubTotal</th>
			</tr>
		</thead>
		<tbody>

		    {% for key,value in request.session.cart.items %}



		    <tr>
		        <td><img class="cpi" width="100px" src="{{value.photo}}" alt=""></td>
		        <td>{{value.name}}</td>
		        <td>{{value.price}} TK</td>
		        <td>{{value.quantity}}</td>
		        <td>
		            <a href="{% url "cart:item_increment" value.title %}">+</a>&nbsp;
		            <a href="{% url "cart:item_decrement" value.title %}">-</a>&nbsp;
		            <a href="{% url "cart:item_clear" value.title %}">Clear</a>&nbsp;
		        </td>

					<td> {{value.st}} TK</td>


		    </tr>

		    {% endfor %}
		    <tr>
		        <td colspan="6" align="right"><b>Total: </b>{{total}} TK</td>
		    </tr>
		    <tr>
		        <td colspan="5" align="right">
		            <a onclick="return confirm('Are You Sure')" class="clearcart btn btn-danger" href="{% url "cart:cart_clear"  %}">Clear cart</a>
		        </td>
		        <td colspan="5" align="right">
		            <a class="btn btn-primary buynow" href="{% url "cart:checkout" %}">Buy now</a>
		        </td>
		</tr>
		</tbody>
	</table>
	 <a class="btn btn-primary buynow" href="{% url "pages:all_products" %}">Continue Shopping</a>
  </div>




{% endblock content %}

templates/cart/checkout.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}


  <div class="col-md-12">
		<div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{{user.profile.image.url}}" alt="" width="72" height="72">
        <h2>Checkout form</h2>
        <p class="lead">Thank You for purchesing from us ^_^</p>
      </div>

      <div class="row">
        <div class="col-md-6 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{request.session.cart | length}}</span>
          </h4>
          <ul class="list-group mb-3">
			{% for key,value in request.session.cart.items %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{value.name}}</h6>
               </div>
               <span class="text-muted">Quantity {{value.quantity }}</span>
              <span class="text-muted">{{value.price}} TK</span>
            </li>
            {% endfor %}

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (BDT)</span>
              <strong>{{total}} TK</strong>
            </li>
          </ul>


        </div>

        <div class="col-md-6 order-md-1">
          <h4 class="mb-3">Billing address</h4>
          <form class="needs-validation" novalidate method="POST" action="{% url "cart:confrm_checkout" %}">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="" value="{{request.user.username}}" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Phone Number</label>
                <input type="text" class="form-control" name="phonenumber" id="phonenumber" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid Phone Number name is required.
                </div>
              </div>
            </div>



            <div class="mb-3">
              <label for="email">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" name="email" class="form-control" id="email" placeholder="you@example.com" value="{{request.user.email}}">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="mb-3">
              <label for="address">Address</label>
              <input type="text" class="form-control" name="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>




            
            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>

            <hr class="mb-4">
            <input class="btn btn-primary btn-sm" value="Confirm" type="submit">
            <a href="{% url "pages:all_products" %}" class="float-right btn btn-primary btn-sm" type="submit">Continue Shopping</a>


          </form>
          
        </div>
      </div>
  </div>




{% endblock content %}

templates/cart/confirm.html
{% extends "base.html" %} 
{% block title %} 
{{title}} 
{% endblock title %} 

{% block content %}

<div class="col-md-12"></div>

{% endblock content %}