cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('add/<slug:slug>/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<slug:slug>/',views.item_clear , name='item_clear'),
    path('item_increment/<slug:slug>/',views.item_increment , name='item_increment'),
    path('item_decrement/<slug:slug>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views



app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<slug:slug>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),

]

users/urls.py
from django.urls import path
from . import views



app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout , name='logout'),
    path('dashboard/', views.dashboard , name='dashboard'),
    path('<int:user_id>/profile/', views.profile , name='profile'),
    # path('myposts/', views.myposts , name='myposts'),
]

templates/partials/_footer.html
 <footer class="footer">
      <div class="container">
        <span class="text-muted">Made by Moin Uddin Ahmed</span>
      </div>
    </footer>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url "pages:home" %}"><h1>EStore</h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url "pages:home" %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "pages:about" %}">About</a>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right mr-7">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "users:dashboard"%}">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "users:profile" user.id %}">Profile</a>
        </li>
        <li class="nav-item mr-3">
          <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
          <i class="fas fa-sign-out-alt"></i> Logout
          </a>

           <form  method="post" id="logout" action="{% url "users:logout" %}">
              {% csrf_token %}
              <input type="hidden">
          </form>
       </li>
       {% if request.session.cart %}
        <li class="nav-item">
        <a href="{% url "cart:cart_detail" %}" class="nav-link">
          <i class="fa fa-cart-plus" style="font-size:30px" aria-hidden="true"></i>
          <strong class="text-info">({{request.session.cart | length}}) Item</strong>
        </a>
      </li>
      {% endif %}
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url "users:register" %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "users:login" %}">Login</a>
      </li>
      {% endif %}


    </ul>


  </div>
</nav>

templates/partials/_sidebar.html
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>Sidebar
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>