cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('add/<slug:slug>/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<slug:slug>/',views.item_clear , name='item_clear'),
    path('item_increment/<slug:slug>/',views.item_increment , name='item_increment'),
    path('item_decrement/<slug:slug>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views



app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<slug:slug>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),

]

templates/ecom/about.html
{% extends "base.html" %} 
{% block title %} 
{{title}} 
{% endblock title %} 

{% block content %}

<div class="col-md-12">
  <p>This is built for CSE470 Project.</p>
</div>

{% endblock content %}

templates/ecom/all_products.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

<div class="col-md-4">
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url "pages:home" %}">Home</a></li>
	</ul>
  </div>

	 <div class="col-md-8">
	 	<div class="row">
			{% for p in products %}
			<div class="col-md-4 mt-4">
				<div class="card-deck-wrapper">
					<div class="card-deck">
						<div class="card">
							<img class="card-img-top" height="250px" src="{{p.photo.url}}" alt="Card image cap">
							<div class="card-block">
								<h4 class="card-title text-center text-secondary"><b><a href="{% url "pages:product_by_slug" p.slug %}">{{p.title}}</a></b></h4>
                <small> <p>{{p.summary}} <a href="{% url "pages:product_by_slug" p.slug %}">Read More</a></p></small>
					<br>
					
					<a href="{% url "cart:cart_add" p.slug %}">Add to cart</a><br>
								<p class="card-text"><h6 class="text-info font-weight-bold">Price: {{p.price}} TK</h6>
					  <strong>Category: </strong><a href="{% url "pages:category_by_slug" p.category.slug %}">{{p.category.title}}</a><br>
								
								</p>
							</div>
						</div>
					</div>
				</div>
			  </div>
  {% endfor %}
	 	</div>
	 </div>



       <div class="mx-auto mt-4 clearfix">

          {% if products.has_other_pages %}

            <ul class="pagination">
               {% if products.has_previous %}
                  <li class="page-item">
                    <a href="?page={{products.previous_page_number}}" class="page-link">&laquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&laquo;</a>
                   </li>
               {% endif %}
               {% for i in products.paginator.page_range %}
                 {% if products.number == i %}

                  <li class="page-item active">
                    <a class="page-link">{{i}}</a>
                  </li>
                 {% else %}
                      <li class="page-item">
                        <a href="?page={{i}}" class="page-link">{{i}}</a>
                      </li>
                 {% endif %}
               {% endfor %}
               {% if products.has_next %}
                  <li class="page-item">
                    <a href="?page={{products.next_page_number}}" class="page-link">&raquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&raquo;</a>
                   </li>
               {% endif %}
            </ul>

          {% else %}

          {% endif %}

  </div>



{% endblock content %}

templates/ecom/index.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

  <div class="col-md-4">
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url "pages:all_products" %}">All Products</a></li>
		{% for cat in categories %}
			<li class="list-group-item"><a href="{% url "pages:category_by_slug" cat.slug %}">{{cat.title}}</a></li>
		{% endfor %}


	</ul>
  </div>


	 <div class="col-md-8">
	 	<div class="row">
			{% for p in products %}
			<div class="col-md-4 mt-4">
				<div class="card-deck-wrapper">
					<div class="card-deck">
						<div class="card">
							<img class="card-img-top" src="{{p.photo.url}}" alt="Card image cap">
							<div class="card-block">
								<h4 class="card-title text-center text-secondary"><b><a href="{% url "pages:product_by_slug" p.slug %}">{{p.title}}</a></b></h4>
                
                <small> <p>{{p.summary}} <a href="{% url "pages:product_by_slug" p.slug %}">Read More</a></p></small>
					<br>
					
					<a href="{% url "cart:cart_add" p.slug %}">Add to cart</a>
								<p class="card-text"><h6 class="text-info font-weight-bold">Price: {{p.price}} TK</h6>
					  <strong>Category: </strong><a href="{% url "pages:category_by_slug" p.category.slug %}">{{p.category.title}}</a><br>
								
								</p>
							</div>
						</div>
					</div>
				</div>
			  </div>
  {% endfor %}
	 	</div>
	 </div>

  <div class="mx-auto mt-4 clearfix">

          {% if products.has_other_pages %}

            <ul class="pagination">
               {% if products.has_previous %}
                  <li class="page-item">
                    <a href="?page={{products.previous_page_number}}" class="page-link">&laquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&laquo;</a>
                   </li>
               {% endif %}
               {% for i in products.paginator.page_range %}
                 {% if products.number == i %}

                  <li class="page-item active">
                    <a class="page-link">{{i}}</a>
                  </li>
                 {% else %}
                      <li class="page-item">
                        <a href="?page={{i}}" class="page-link">{{i}}</a>
                      </li>
                 {% endif %}
               {% endfor %}
               {% if products.has_next %}
                  <li class="page-item">
                    <a href="?page={{products.next_page_number}}" class="page-link">&raquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&raquo;</a>
                   </li>
               {% endif %}
            </ul>

          {% else %}

          {% endif %}

  </div>



{% endblock content %}

templates/ecom/show.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

  <div class="col-md-4 mt-4">
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url "pages:home" %}">Home</a></li>
	</ul>
  </div>
  <div class="col-md-8 mt-4">
	<h1 class="page-header">{{product.title}}</h1>
	<img  src="{{product.photo.url}}" width="400px" class="img-thumbnail" alt="">
    <br>
    <p>{{product.description}}</p>
    <p>Price : {{product.price}} TK</p>
    <p>Avaiable : {{product.quantity}}</p>
    <p>Added on: {{product.published_at}}</p>
    <p><a class="btn btn-primary buynow" href="{% url "cart:cart_add" product.slug %}">Add to cart</a></p>

  </div>




{% endblock content %}